version: '3'

services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    expose:
      - '3306'
    restart: always
    env_file:
      - .env

networks:
  inception:
    driver: brige
