version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp-volume:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  db-volume:
    driver_opts:
      device: /home/hunpark/data/db-data
      type: none
      o: bind

  wp-volume:
    driver_opts:
      device: /home/hunpark/data/wp-data
      type: none
      o: bind
