version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    expose:
      - "3306"
    restart: always
    env_file:
      - .env

networks:
  inception:
    driver: bridge

volumes:
  db-volume:
    driver_opts:
      device: /home/hunpark/data/db-data
      type: none
      o: bind
